# Top-level configuration
name = "reviews-admin"
main = "src/index.js"
compatibility_date = "2023-05-05"

# workers_dev = false
# route = { pattern = "example.org/*", zone_name = "example.org" }

# kv_namespaces = [
#  { binding = "<MY_NAMESPACE>", id = "<KV_ID>" }
#]

# [env.staging]
# name = "my-worker-staging"
# route = { pattern = "staging.example.org/*", zone_name = "example.org" }

# kv_namespaces = [
#  { binding = "<MY_NAMESPACE>", id = "<STAGING_KV_ID>" }
#]